import {
  ArrowCounterClockwise,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  ArrowUUpLeft,
  CaretDown,
  CaretLeft,
  CaretRight,
  ChartLineUp,
  ChatCircle,
  Check,
  ClockCounterClockwise,
  CursorClick,
  DotsThree,
  Eye,
  FileText,
  Folders,
  GearSix,
  Hand,
  ListBullets,
  ListChecks,
  Lightning,
  MagnifyingGlass,
  MathOperations,
  PencilSimple,
  PencilLine,
  Plus,
  Robot,
  SealCheck,
  ShareNetwork,
  ShoppingBagOpen,
  Trash,
  UserCircle,
  UsersThree,
  X,
} from '@phosphor-icons/react';

export const AppIcons = {
  Accepted: SealCheck,
  Activity: ListChecks,
  Agent: Robot,
  Back: ArrowLeft,
  Check,
  Close: X,
  CollapseDown: CaretDown,
  CollapseLeft: CaretLeft,
  CollapseRight: CaretRight,
  Collaborators: UsersThree,
  Comments: ChatCircle,
  Commerce: ShoppingBagOpen,
  File: FileText,
  History: ClockCounterClockwise,
  Items: ListBullets,
  More: DotsThree,
  New: Plus,
  Open: ArrowRight,
  OpenExternal: ArrowSquareOut,
  Outcome: ChartLineUp,
  Delete: Trash,
  Person: UserCircle,
  Projects: Folders,
  Rename: PencilSimple,
  Reset: ArrowCounterClockwise,
  Restore: ArrowUUpLeft,
  Search: MagnifyingGlass,
  Settings: GearSix,
  Select: CursorClick,
  Sketch: PencilLine,
  SketchConstraints: MathOperations,
  Share: ShareNetwork,
  View: Eye,
  Pan: Hand,
  Capability: Lightning,
} as const;
