import {
  ArrowCounterClockwise,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  ArrowUUpLeft,
  CaretDown,
  CaretLeft,
  CaretRight,
  ChartLineUp,
  ChatCircle,
  Check,
  ClockCounterClockwise,
  CursorClick,
  DotsThree,
  FileText,
  Folders,
  FrameCorners,
  ListChecks,
  Lightning,
  MagnifyingGlass,
  Robot,
  SealCheck,
  ShareNetwork,
  ShoppingBagOpen,
  UserCircle,
  UsersThree,
  X,
} from '@phosphor-icons/react';

export const AppIcons = {
  Accepted: SealCheck,
  Activity: ListChecks,
  Agent: Robot,
  Back: ArrowLeft,
  Brand: FrameCorners,
  Check,
  Close: X,
  CollapseDown: CaretDown,
  CollapseLeft: CaretLeft,
  CollapseRight: CaretRight,
  Collaborators: UsersThree,
  Comments: ChatCircle,
  Commerce: ShoppingBagOpen,
  File: FileText,
  History: ClockCounterClockwise,
  More: DotsThree,
  Open: ArrowRight,
  OpenExternal: ArrowSquareOut,
  Outcome: ChartLineUp,
  Person: UserCircle,
  Projects: Folders,
  Reset: ArrowCounterClockwise,
  Restore: ArrowUUpLeft,
  Search: MagnifyingGlass,
  Select: CursorClick,
  Share: ShareNetwork,
  Capability: Lightning,
} as const;
