import {
  ArrowCounterClockwiseIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowSquareOutIcon,
  ArrowUUpLeftIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  ChartLineUpIcon,
  ChatCircleIcon,
  CheckIcon,
  ClockCounterClockwiseIcon,
  DotsThreeIcon,
  EyeIcon,
  FileTextIcon,
  FoldersIcon,
  GearSixIcon,
  HandIcon,
  ListChecksIcon,
  LightningIcon,
  MagnifyingGlassIcon,
  MathOperationsIcon,
  PencilSimpleIcon,
  PlusIcon,
  RobotIcon,
  SealCheckIcon,
  ShareNetworkIcon,
  ShoppingBagOpenIcon,
  TrashIcon,
  UserCircleIcon,
  UsersThreeIcon,
  XIcon,
  NavigationArrowIcon,
  PenNibIcon,
  StackSimpleIcon,
  ClockIcon,
  FileDashedIcon,
  VectorTwoIcon,
  ShuffleSimpleIcon,
  EqualsIcon,
  PauseIcon,
  ArrowsHorizontalIcon,
  AngleIcon,
  MinusIcon,
  LineVerticalIcon,
  CirclesThreeIcon,
  TargetIcon,
  BezierCurveIcon,
  ChartPieSliceIcon,
  LockIcon,
  LineSegmentIcon,
  CircleNotchIcon,
  CircleIcon,
  RectangleIcon,
  PolygonIcon,
  ScissorsIcon,
  HardHatIcon,
} from '@phosphor-icons/react';

const ConstraintIcons = {
  Perpendicular: VectorTwoIcon,
  Coincident: ShuffleSimpleIcon,
  Equal: EqualsIcon,
  Parallel: PauseIcon,
  Dimension: ArrowsHorizontalIcon,
  Angle: AngleIcon,
  Horizontal: MinusIcon,
  Vertical: LineVerticalIcon,
  Concentric: TargetIcon,
  Tangent: BezierCurveIcon,
  Radius: ChartPieSliceIcon,
  Fixed: LockIcon,
  RadialPattern: CirclesThreeIcon,
} as const;

const PrimitiveIcons = {
  Line: LineSegmentIcon,
  Circle: CircleIcon,
  Arc: CircleNotchIcon,
  Ellipse: CircleIcon,
  Rectangle: RectangleIcon,
  BSpline: BezierCurveIcon,
  Polygon: PolygonIcon,
  Trim: ScissorsIcon,
} as const;

export const AppIcons = {
  Accepted: SealCheckIcon,
  Activity: ListChecksIcon,
  Agent: RobotIcon,

  Back: ArrowLeftIcon,
  Check: CheckIcon,
  Close: XIcon,

  CollapseDown: CaretDownIcon,
  CollapseLeft: CaretLeftIcon,
  CollapseRight: CaretRightIcon,

  Collaborators: UsersThreeIcon,
  Comments: ChatCircleIcon,
  Commerce: ShoppingBagOpenIcon,

  Draft: FileDashedIcon,

  File: FileTextIcon,
  History: ClockCounterClockwiseIcon,
  Items: StackSimpleIcon,
  More: DotsThreeIcon,

  New: PlusIcon,
  Open: ArrowRightIcon,
  OpenExternal: ArrowSquareOutIcon,

  Outcome: ChartLineUpIcon,
  Delete: TrashIcon,
  Person: UserCircleIcon,
  Projects: FoldersIcon,

  Rename: PencilSimpleIcon,
  Reset: ArrowCounterClockwiseIcon,
  Restore: ArrowUUpLeftIcon,
  Recent: ClockIcon,

  Search: MagnifyingGlassIcon,
  Settings: GearSixIcon,
  MakerProfile: HardHatIcon,
  Select: NavigationArrowIcon,

  Sketch: PenNibIcon,
  SketchConstraints: MathOperationsIcon,

  Share: ShareNetworkIcon,
  View: EyeIcon,
  Pan: HandIcon,

  Capability: LightningIcon,

  ...ConstraintIcons,
  ...PrimitiveIcons,
} as const;
